[package]
name = "jxr"
version = "0.1.0"
authors = ["Joe Moon <joe@xoxomoon.com>"]

[dependencies]
pulldown-cmark = "0.0.11"
clap = "2.29.0"
walkdir = "2"
serde = "1"
serde_derive = "1"
serde_json = "1"
serde_yaml = "0.7"
lazy_static = "1"
regex = "0.2"
chrono = "0.4"
handlebars = "0.29"
